# Generated by Django 4.1 on 2023-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0003_alter_pickup_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("pincode", models.PositiveIntegerField()),
            ],
        ),
    ]
