# Generated by Django 4.1 on 2023-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0004_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="pincode",
        ),
        migrations.AddField(
            model_name="buyer",
            name="password",
            field=models.CharField(default=None, max_length=128),
        ),
    ]
