# Generated by Django 4.1 on 2023-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0008_pickup_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickup",
            name="pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
