# Generated by Django 4.1 on 2023-07-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0009_alter_pickup_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickup",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
