# Generated by Django 4.1 on 2023-07-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0010_alter_pickup_pincode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickup",
            name="pincode",
        ),
        migrations.AddField(
            model_name="pickup",
            name="zipcode",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
