# Generated by Django 4.1 on 2023-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0012_remove_pickup_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickup",
            name="pincode",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
