# Generated by Django 4.1 on 2023-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0013_pickup_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickup",
            name="pincode",
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
