# Generated by Django 4.1 on 2023-07-02 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0015_alter_pickup_pincode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickup",
            name="address",
        ),
        migrations.RemoveField(
            model_name="pickup",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="pickup",
            name="time",
        ),
    ]
