# Generated by Django 4.1 on 2023-07-02 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0016_remove_pickup_address_remove_pickup_pincode_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pickup",
        ),
    ]
