# Generated by Django 4.1 on 2023-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0017_delete_pickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=128, null=True)),
                ("pincode", models.CharField(default=None, max_length=6, null=True)),
            ],
        ),
    ]
