# Generated by Django 4.1 on 2023-07-02 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0018_pickup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickup",
            name="pincode",
        ),
    ]
