# Generated by Django 4.1 on 2023-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapapp", "0019_remove_pickup_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickup",
            name="pincode",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
